/**
 * Vendors the editor typefaces into src/fonts so the app works offline
 * (Tauri's CSP blocks remote font hosts anyway).
 *
 * Every family here is open source and part of Open Foundry's catalogue
 * (open-foundry.com); the binaries come from Google Fonts, which serves the
 * same upstream OFL releases.
 *
 *   node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile, rm } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = resolve(ROOT, "src/fonts");

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const FAMILIES = [
  { id: "work-sans", query: "Work+Sans:ital,wght@0,300..700;1,300..700" },
  { id: "karla", query: "Karla:ital,wght@0,300..700;1,300..700" },
  { id: "vollkorn", query: "Vollkorn:ital,wght@0,400..700;1,400..700" },
  {
    id: "libre-baskerville",
    query: "Libre+Baskerville:ital,wght@0,400;0,700;1,400",
  },
  {
    id: "space-mono",
    query: "Space+Mono:ital,wght@0,400;0,700;1,400;1,700",
  },
];

/** Latin-only: the other subsets triple the payload for no benefit here. */
const KEEP_SUBSETS = new Set(["latin", "latin-ext"]);

async function cssFor(query) {
  const res = await fetch(
    `https://fonts.googleapis.com/css2?family=${query}&display=swap`,
    { headers: { "User-Agent": UA } },
  );
  if (!res.ok) throw new Error(`css2 ${query}: ${res.status}`);
  return res.text();
}

/** Split a Google Fonts stylesheet into `/* subset *\/` + @font-face pairs. */
function faceBlocks(css) {
  const out = [];
  const re = /\/\*\s*([\w-\[\]]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  let m;
  while ((m = re.exec(css))) out.push({ subset: m[1], block: m[2] });
  return out;
}

await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });

const chunks = [
  "/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */",
  "/* Open-source families from open-foundry.com, binaries via Google Fonts. */",
  "",
];

for (const family of FAMILIES) {
  const blocks = faceBlocks(await cssFor(family.query)).filter((b) =>
    KEEP_SUBSETS.has(b.subset),
  );
  if (!blocks.length) throw new Error(`no latin faces for ${family.id}`);

  let n = 0;
  for (const { subset, block } of blocks) {
    const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
    if (!url) continue;
    const file = `${family.id}-${subset}-${n++}.woff2`;
    const bin = await fetch(url, { headers: { "User-Agent": UA } });
    if (!bin.ok) throw new Error(`${url}: ${bin.status}`);
    await writeFile(
      resolve(OUT, file),
      Buffer.from(await bin.arrayBuffer()),
    );
    chunks.push(block.replace(url, `./${file}`), "");
    console.log(`${family.id}  ${subset}  ${file}`);
  }
}

await writeFile(resolve(OUT, "fonts.css"), chunks.join("\n"));
console.log(`\nwrote ${OUT}/fonts.css`);
