// Generated by scripts/sync-version.mjs from CHANGELOG.md. Do not edit.
export const RELEASE_VERSION = "0.2.0";
export const RELEASE_NOTES = "### Minor Changes\n\n- Anonymous usage counts, so the app can be improved by something other than\n  guesswork — which views get used, which settings get changed, how often files\n  get saved. Nobody is identified, and no file name, path, or word of your\n  writing ever leaves the machine. Settings → Privacy turns it off.";
