// Generated by scripts/sync-version.mjs from CHANGELOG.md. Do not edit.
export const RELEASE_VERSION = "0.1.0";
export const RELEASE_NOTES = "### Minor Changes\n\n- First release. A WYSIWYG editor for the plans folders across your local git\n  repositories: a file tree over every repo you open, three views of the same\n  buffer — write, source and diff — frontmatter held apart from the prose,\n  folders and drag-and-drop, a command palette, and a git panel that stages,\n  commits and pushes without leaving the app. It updates itself, and shows you\n  what changed when it does.";
